# Generated by Django 4.1.7 on 2024-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membars',
            fields=[
                ('indx', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=120)),
                ('gmail', models.CharField(max_length=120)),
                ('packages', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
            ],
        ),
    ]
