# Generated by Django 4.1.7 on 2024-11-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
    ]
