# Generated by Django 4.1.7 on 2025-02-27 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gymapp', '0005_gymplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymplan',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
