# Generated by Django 4.1.7 on 2025-09-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gymapp', '0006_gymplan_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gymplan',
        ),
    ]
